/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CreamAccountDataProvider,
  CreamAccountDataProviderInterface,
} from "../CreamAccountDataProvider";

const _abi = [
  {
    inputs: [],
    name: "EXP_SCALE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "comptroller",
    outputs: [
      {
        internalType: "contract IComptroller",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getUserAccountData",
    outputs: [
      {
        internalType: "uint256",
        name: "totalCollateralInEth",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalBorrowInEth",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "healthFactor",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ethPerUsd",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getUserReserveData",
    outputs: [
      {
        internalType: "uint256",
        name: "balanceUnderlying",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "debtUnderlying",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "exchangeRateStored",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "borrowRatePerBlock",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "supplyRatePerBlock",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isUnderThresholdHealthFactor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CreamAccountDataProvider__factory {
  static readonly abi = _abi;
  static createInterface(): CreamAccountDataProviderInterface {
    return new utils.Interface(_abi) as CreamAccountDataProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CreamAccountDataProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CreamAccountDataProvider;
  }
}
