/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICTokenFlashLoan,
  ICTokenFlashLoanInterface,
} from "../ICTokenFlashLoan";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "flashLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICTokenFlashLoan__factory {
  static readonly abi = _abi;
  static createInterface(): ICTokenFlashLoanInterface {
    return new utils.Interface(_abi) as ICTokenFlashLoanInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICTokenFlashLoan {
    return new Contract(address, _abi, signerOrProvider) as ICTokenFlashLoan;
  }
}
