/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILoanSaver, ILoanSaverInterface } from "../ILoanSaver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getUserProtectionAt",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getUserProtectionCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isUnderThresholdHealthFactor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "protectionId",
        type: "bytes32",
      },
    ],
    name: "saveLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILoanSaver__factory {
  static readonly abi = _abi;
  static createInterface(): ILoanSaverInterface {
    return new utils.Interface(_abi) as ILoanSaverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILoanSaver {
    return new Contract(address, _abi, signerOrProvider) as ILoanSaver;
  }
}
