/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CreamLoanSaverInterface extends ethers.utils.Interface {
  functions: {
    "CUSDC_ADDRESS()": FunctionFragment;
    "EXP_SCALE()": FunctionFragment;
    "GELATO()": FunctionFragment;
    "comptroller()": FunctionFragment;
    "executeOperation(address,address,uint256,uint256,bytes)": FunctionFragment;
    "flashFeeBps()": FunctionFragment;
    "getUserAccountData(address)": FunctionFragment;
    "getUserProtectionAt(address,uint256)": FunctionFragment;
    "getUserProtectionCount(address)": FunctionFragment;
    "getUserProtectionData(bytes32)": FunctionFragment;
    "getUserReserveData(address,address)": FunctionFragment;
    "isUnderThresholdHealthFactor(address)": FunctionFragment;
    "oracle()": FunctionFragment;
    "pokeMe()": FunctionFragment;
    "protectionFeeBps()": FunctionFragment;
    "saveLoan(address,bytes32)": FunctionFragment;
    "uniswapRouter()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CUSDC_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "EXP_SCALE", values?: undefined): string;
  encodeFunctionData(functionFragment: "GELATO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "comptroller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeOperation",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flashFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAccountData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProtectionAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProtectionCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProtectionData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReserveData",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isUnderThresholdHealthFactor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "pokeMe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protectionFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "saveLoan",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CUSDC_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "EXP_SCALE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GELATO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "comptroller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flashFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAccountData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProtectionAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProtectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProtectionData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReserveData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUnderThresholdHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pokeMe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protectionFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "saveLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;

  events: {};
}

export class CreamLoanSaver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CreamLoanSaverInterface;

  functions: {
    CUSDC_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    EXP_SCALE(overrides?: CallOverrides): Promise<[BigNumber]>;

    GELATO(overrides?: CallOverrides): Promise<[string]>;

    comptroller(overrides?: CallOverrides): Promise<[string]>;

    executeOperation(
      sender: string,
      arg1: string,
      arg2: BigNumberish,
      premiums: BigNumberish,
      params: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    flashFeeBps(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUserAccountData(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalCollateralInEth: BigNumber;
        totalBorrowInEth: BigNumber;
        healthFactor: BigNumber;
        ethPerUsd: BigNumber;
      }
    >;

    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getUserProtectionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUserProtectionData(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, string, string] & {
          thresholdHealthFactor: BigNumber;
          wantedHealthFactor: BigNumber;
          colToken: string;
          debtToken: string;
        }
      ]
    >;

    getUserReserveData(
      asset: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        balanceUnderlying: BigNumber;
        debtUnderlying: BigNumber;
        exchangeRateStored: BigNumber;
        borrowRatePerBlock: BigNumber;
        supplyRatePerBlock: BigNumber;
      }
    >;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    pokeMe(overrides?: CallOverrides): Promise<[string]>;

    protectionFeeBps(overrides?: CallOverrides): Promise<[BigNumber]>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapRouter(overrides?: CallOverrides): Promise<[string]>;
  };

  CUSDC_ADDRESS(overrides?: CallOverrides): Promise<string>;

  EXP_SCALE(overrides?: CallOverrides): Promise<BigNumber>;

  GELATO(overrides?: CallOverrides): Promise<string>;

  comptroller(overrides?: CallOverrides): Promise<string>;

  executeOperation(
    sender: string,
    arg1: string,
    arg2: BigNumberish,
    premiums: BigNumberish,
    params: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  flashFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

  getUserAccountData(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      totalCollateralInEth: BigNumber;
      totalBorrowInEth: BigNumber;
      healthFactor: BigNumber;
      ethPerUsd: BigNumber;
    }
  >;

  getUserProtectionAt(
    account: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getUserProtectionCount(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUserProtectionData(
    id: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, string] & {
      thresholdHealthFactor: BigNumber;
      wantedHealthFactor: BigNumber;
      colToken: string;
      debtToken: string;
    }
  >;

  getUserReserveData(
    asset: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      balanceUnderlying: BigNumber;
      debtUnderlying: BigNumber;
      exchangeRateStored: BigNumber;
      borrowRatePerBlock: BigNumber;
      supplyRatePerBlock: BigNumber;
    }
  >;

  isUnderThresholdHealthFactor(
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  oracle(overrides?: CallOverrides): Promise<string>;

  pokeMe(overrides?: CallOverrides): Promise<string>;

  protectionFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

  saveLoan(
    account: string,
    protectionId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapRouter(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    CUSDC_ADDRESS(overrides?: CallOverrides): Promise<string>;

    EXP_SCALE(overrides?: CallOverrides): Promise<BigNumber>;

    GELATO(overrides?: CallOverrides): Promise<string>;

    comptroller(overrides?: CallOverrides): Promise<string>;

    executeOperation(
      sender: string,
      arg1: string,
      arg2: BigNumberish,
      premiums: BigNumberish,
      params: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    flashFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

    getUserAccountData(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalCollateralInEth: BigNumber;
        totalBorrowInEth: BigNumber;
        healthFactor: BigNumber;
        ethPerUsd: BigNumber;
      }
    >;

    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getUserProtectionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserProtectionData(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, string] & {
        thresholdHealthFactor: BigNumber;
        wantedHealthFactor: BigNumber;
        colToken: string;
        debtToken: string;
      }
    >;

    getUserReserveData(
      asset: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        balanceUnderlying: BigNumber;
        debtUnderlying: BigNumber;
        exchangeRateStored: BigNumber;
        borrowRatePerBlock: BigNumber;
        supplyRatePerBlock: BigNumber;
      }
    >;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    oracle(overrides?: CallOverrides): Promise<string>;

    pokeMe(overrides?: CallOverrides): Promise<string>;

    protectionFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapRouter(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    CUSDC_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    EXP_SCALE(overrides?: CallOverrides): Promise<BigNumber>;

    GELATO(overrides?: CallOverrides): Promise<BigNumber>;

    comptroller(overrides?: CallOverrides): Promise<BigNumber>;

    executeOperation(
      sender: string,
      arg1: string,
      arg2: BigNumberish,
      premiums: BigNumberish,
      params: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    flashFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

    getUserAccountData(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserProtectionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserProtectionData(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserReserveData(
      asset: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    pokeMe(overrides?: CallOverrides): Promise<BigNumber>;

    protectionFeeBps(overrides?: CallOverrides): Promise<BigNumber>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapRouter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CUSDC_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    EXP_SCALE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GELATO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    comptroller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeOperation(
      sender: string,
      arg1: string,
      arg2: BigNumberish,
      premiums: BigNumberish,
      params: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    flashFeeBps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserAccountData(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserProtectionCount(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserProtectionData(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserReserveData(
      asset: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pokeMe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protectionFeeBps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
