/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ILoanSaverInterface extends ethers.utils.Interface {
  functions: {
    "getUserProtectionAt(address,uint256)": FunctionFragment;
    "isUnderThresholdHealthFactor(address)": FunctionFragment;
    "saveLoan(address,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getUserProtectionAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isUnderThresholdHealthFactor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "saveLoan",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getUserProtectionAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUnderThresholdHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "saveLoan", data: BytesLike): Result;

  events: {};
}

export class ILoanSaver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ILoanSaverInterface;

  functions: {
    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { protectionId: string }>;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getUserProtectionAt(
    account: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  isUnderThresholdHealthFactor(
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  saveLoan(
    account: string,
    protectionId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getUserProtectionAt(
      account: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isUnderThresholdHealthFactor(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    saveLoan(
      account: string,
      protectionId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
